{
 "title": "Docker Monitor",
 "description": "Docker Monitoring Template",
 "tags": [ "docker" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "container",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total,name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Up Time",
   "type": "gauge",
   "description": "Container Up Time",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{name=\"$container\"}",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Container Memory Rss",
   "type": "gauge",
   "description": "RSS stands for Resident Set Size and shows how much RAM is utilized at the time the command is output.",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(name) (container_memory_rss{name=\"$container\"})",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Container Memory usage",
   "type": "candlestick",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sort_desc(sum(container_memory_usage_bytes{name=\"$container\"} / 1024 * 1024 ) by (name))",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Container CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(container_cpu_user_seconds_total{image!=\"\"}) by (name))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Memory Rss",
   "type": "timeseries",
   "description": "RSS stands for Resident Set Size and shows how much RAM is utilized at the time the command is output.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(name) (container_memory_rss{name!=\"\"})",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(container_memory_usage_bytes{image!=\"\"}) by (name))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Total Network i/o",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum by (container_name) (rate(container_network_receive_bytes_total{image!=\"\"}[1m] ) )",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum by (container_name) (rate(container_network_transmit_bytes_total{image!=\"\"}[1m] ) )",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes - container_fs_usage_bytes) / sum(container_fs_limit_bytes)"
    }
   ]
  }
 ]
}